Sitewise
awslabs/aws-iot-greengrass-accelerators pull request #33
Opened 2023-01-29 10:32 UTC by maximcherny

*Issue #, if available:* n/a

*Description of changes:* created a new SIteWise accelerator for ingestion of data from an OPC UA-compatible endpoint to be streamed into AWS IoT SiteWise. This accelerator is to form basis for two of the existing workshops, namely IIoT Security and IoT analytics. The accelerator follows the pre-existing pattern used to create other V2 accelerators, namely `etl_simple` and `os_cmd`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-02-08 19:23 UTC, gadams999 commented on README.md
> +- [SiteWise Deployment](v2/sitewise)
AWS IoT SiteWise to be consistent with service naming.

2023-02-08 19:23 UTC, gadams999 commented on v2/README.md
> +- [SiteWise Deployment](sitewise)
AWS IoT SiteWise

2023-02-08 19:37 UTC, gadams999 commented on v2/sitewise/README.md
> +# AWS IoT Greengrass V2 SiteWise Deployment
AWS IoT SiteWise

2023-02-08 19:37 UTC, gadams999 commented on v2/sitewise/README.md
> +This deployment, SiteWise Deployment, extends the capabilities of the [base](../base) accelerator stack by adding a new thing group, and Greengrass deployment for the existing Greengrass core. The fu
AWS IoT SiteWise

2023-02-08 19:39 UTC, gadams999 commented on v2/sitewise/README.md
> +## SiteWise Deployment Use Case
AWS IoT SiteWise

2023-02-08 19:39 UTC, gadams999 commented on v2/sitewise/README.md
> +![SiteWise Deployment Architecture](docs/arch.svg)
AWS IoT SiteWise

2023-02-08 19:40 UTC, gadams999 commented on v2/sitewise/README.md
> +1. The SiteWise edge publisher component publishes the data to AWS IoT SiteWise, via the newly created SiteWise gateway associated with the Greengrass deployment.
IoT SiteWise publisher

2023-02-08 19:41 UTC, gadams999 commented on v2/sitewise/README.md
> +sitewise
Suggest changing to `aws_iot_sitewise`

2023-02-08 19:43 UTC, gadams999 commented on v2/sitewise/README.md
> +In its current form, no. This component is not suitable for production workloads and intended to demonstrate the capabilities of Greengrass for data ingestion using OPC UA. To be production-ready wou
AWS IoT Greengrass.

2023-02-08 19:44 UTC, gadams999 commented on v2/sitewise/cdk/bin/app.ts
> +  description: "Greengrass Accelerator v2 - SiteWise Component"
Greengrass Accelerator v2 - AWS IoT SiteWise Component

I think it's fine to use shorted names in the code, but for any descriptive output or reference, such as stack name, full service name is more consistent.

2023-02-08 19:56 UTC, gadams999 requested changes
If you could make the doc and folder layout, I'll then exercise the accelerators.

2023-02-09 00:05 UTC, maximcherny commented
@gadams999 thanks for reviewing, I've gone through and made the suggested changes.

2023-03-06 19:44 UTC, merged